#!/bin/bash
##########################################
# desc: Aktualisiert alle steam apps
# autor: seevenup
# version: 0.1
##########################################

PATH_STEAM="/opt/steamcmd"

for app in $(/bin/ls $PATH_STEAM/Steam/steamapps/appmanifest_* | cut -d '_' -f2 | cut -d '.' -f1)
do
	$PATH_STEAM/steamcmd.sh +login svenlauber Cherokee1983 +app_update $app +quit
done

